[build]
command = "hugo --minify"
publish = "public"

[build.environment]
HUGO_VERSION = "0.101.0"
HUGO_ENV = "production"

[[redirects]]
from = "/blog"
to = "/"

[[redirects]]
from = "/2016/:blog"
to = "/:blog"

[[redirects]]
from = "/2017/:blog"
to = "/:blog"

[[redirects]]
from = "/2018/:blog"
to = "/:blog"

[[redirects]]
from = "/blog/2016/:blog"
to = "/:blog"

[[redirects]]
from = "/blog/2017/:blog"
to = "/:blog"

[[redirects]]
from = "/blog/2018/:blog"
to = "/:blog"

[[redirects]]
from = "/coffee"
to = "/coffee"

[[redirects]]
from = "/feed"
to = "/index.xml"

[[redirects]]
from = "/feed/articles"
to = "/articles/index.xml"

[[redirects]]
from = "/semver-deps"
to = "/composer-semver-and-underlying-dependency-changes"

